<?php
   $dbhost = 'localhost';
   $dbuser = 'root';
   $dbpass = '';
   
   $conn = mysql_connect($dbhost, $dbuser, $dbpass);
   
   if(! $conn ) {
      die('Could not connect: ' . mysql_error());
   }
   
   $sql = 'SELECT ownerrollnumber, ownername,owneraddress,ownerphonenumber,owneremail,ownerpic FROM owner';
   $ownername='SELECT ownername FROM owner';
   $ownernamee=mysql_query($ownername);
   $ownerrollnumber='SELECT ownerrollnumber FROM owner';
   $ownerrollnumberr=mysql_query($ownerrollnumber);
   $owneraddress='SELECT owneraddress FROM owner';
   $owneraddresss=mysql_query($owneraddress);
   $ownerphone='SELECT ownerphonenumber FROM owner';
   $ownerphonee=mysql_query($ownerphone);
   $owneremail='SELECT owneremail FROM owner';
   $owneremaill=mysql_query($owneremail);
   $ownerpic='SELECT ownerpic FROM owner';
   $ownerpicc=mysql_query($ownerpic);
   mysql_select_db('gaurav');
   $retval = mysql_query( $sql, $conn );
   
   if(! $retval ) {
      die('Could not get data: ' . mysql_error());
   }
   
   while($row = mysql_fetch_array($retval, MYSQL_ASSOC)) {
echo "<!doctype html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "    <meta charset=\"utf-8\">\n"; 
echo "    <meta name=\"keywords\" content=\"\">\n"; 
echo "    <meta name=\"description\" content=\"\">\n"; 
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=0\">\n"; 
echo "    <link rel=\"shortcut icon\" type=\"image/png\" href=\"favicon.png\">\n"; 
echo "    \n"; 
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/bootstrap.min.css\">\n"; 
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\n"; 
echo "	<link rel=\"stylesheet\" href=\"./css/animate.min.css\"><link rel=\"stylesheet\" href=\"./css/font-awesome.min.css\"><link rel=\"stylesheet\" href=\"./css/linecons.min.css\"><link rel=\"stylesheet\" href=\"./css/ionicons.min.css\"><link href='https://fonts.googleapis.com/css?family=Josefin+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>\n"; 
echo "    \n"; 
echo "	<script src=\"./js/jquery-2.1.0.min.js\"></script>\n"; 
echo "	<script src=\"./js/bootstrap.min.js\"></script>\n"; 
echo "	<script src=\"./js/blocs.min.js\"></script>\n"; 
echo "    <title>Owner Home</title>\n"; 
echo "\n"; 
echo "    \n"; 
echo "<!-- Google Analytics -->\n"; 
echo " \n"; 
echo "<!-- Google Analytics END -->\n"; 
echo "    \n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "<!-- Main container -->\n"; 
echo "<div class=\"page-container\">\n"; 
echo "    \n"; 
echo "<!-- bloc-18 -->\n"; 
echo "<div class=\"bloc bgc-pale-blue l-bloc\" id=\"bloc-18\">\n"; 
echo "	<div class=\"container bloc-sm\">\n"; 
echo "		<nav class=\"navbar row\">\n"; 
echo "			<div class=\"navbar-header\">\n"; 
echo "				<a class=\"navbar-brand\" href=\"index.html\"><img src=\"img/logo.png\" alt=\"logo\" /></a>\n"; 
echo "				<button id=\"nav-toggle\" type=\"button\" class=\"ui-navbar-toggle navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-1\">\n"; 
echo "					<span class=\"sr-only\">Toggle navigation</span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span><span class=\"icon-bar\"></span>\n"; 
echo "				</button>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"collapse navbar-collapse navbar-1\">\n"; 
echo "				<ul class=\"site-navigation nav navbar-nav\">\n"; 
echo "					<li>\n"; 
echo "						<a href=\"index.html\">Home</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"the_team.html\">The Team</a>\n"; 
echo "					</li>\n"; 
echo "					<li>\n"; 
echo "						<a href=\"logout.php\">Logout</a>\n"; 
echo "					</li>\n"; 
echo "				</ul>\n"; 
echo "			</div>\n"; 
echo "		</nav>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "<!-- bloc-18 END -->\n"; 
echo "\n"; 
echo "<!-- bloc-19 -->\n"; 
echo "<div class=\"bloc bgc-white l-bloc \" id=\"bloc-19\">\n"; 
echo "	<div class=\"container bloc-lg\">\n"; 
echo "		<div class=\"row\">\n"; 
echo "			<div class=\"col-sm-6\">\n"; 
echo "				<h1 class=\"mg-md\">\n"; 
echo "				 Hello,$ownernamee\n"; 
echo "				</h1>\n"; 
echo "				<h6 class=\"mg-md\">\n"; 
echo "					<br>\n"; 
echo "				</h6>\n"; 
echo "				<div class=\"row\">\n"; 
echo "					<div class=\"col-sm-4\">\n"; 
echo "						<img src=\"img/DSC08195.jpg\" class=\"img-responsive img-rd-md\" />\n"; 
echo "					</div>\n"; 
echo "					<div class=\"col-sm-8\">\n"; 
echo "						<h3 class=\"mg-md\">\n"; 
echo "							Roll No\n"; 
echo "						</h3>\n"; 
echo "						<h4 class=\"mg-md\">\n"; 
echo "						$ownerrollnumberr\n"; 
echo "						</h4>\n"; 
echo "						<div class=\"divider-h\">\n"; 
echo "							<span class=\"divider\"></span>\n"; 
echo "						</div>\n"; 
echo "						<h3 class=\"mg-md\" >\n"; 
echo "							Email\n"; 
echo "						</h3>\n"; 
echo "						<h4 class=\"mg-md\">\n"; 
echo "						$owneremaill\n"; 
echo "						</h4>\n"; 
echo "						<div class=\"divider-h\">\n"; 
echo "							<span class=\"divider\"></span>\n"; 
echo "						</div>\n"; 
echo "						<h3 class=\"mg-md\">\n"; 
echo "							Phone\n"; 
echo "						</h3>\n"; 
echo "						<h4 class=\"mg-md\">\n"; 
echo "						$ownerphonee\n"; 
echo "						</h4>\n"; 
echo "						<div class=\"divider-h\">\n"; 
echo "							<span class=\"divider\"></span>\n"; 
echo "						</div>\n"; 
echo "						<h3 class=\"mg-md\">\n"; 
echo "							Address\n"; 
echo "						</h3>\n"; 
echo "						<h4 class=\"mg-md\">\n"; 
echo "							$owneraddresss\n"; 
echo "						</h4>\n"; 
echo "						<div class=\"divider-h\">\n"; 
echo "							<span class=\"divider\"></span>\n"; 
echo "						</div>\n"; 
echo "					</div>\n"; 
echo "				</div>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"col-sm-6\">\n"; 
echo "				<h2 class=\"mg-lg\">\n"; 
echo "					<br>\n"; 
echo "				</h2>\n"; 
echo "				<h6 class=\"mg-md\">\n"; 
echo "					<br>\n"; 
echo "				</h6><img src=\"img/1774178.jpg\" class=\"animated vanishIn img-rd-md img-responsive\" height=\"323\" width=\"485\" />\n"; 
echo "				<h2 class=\"mg-lg\">\n"; 
echo "					Manufacturer\n"; 
echo "				</h2>\n"; 
echo "				<h3 class=\"mg-sm\">\n"; 
echo "					Model\n"; 
echo "				</h3>\n"; 
echo "				<p class=\"mg-lg\">\n"; 
echo "					Description <br>Description<br> Description<br>Description\n"; 
echo "				</p>\n"; 
echo "				<div class=\"divider-h\">\n"; 
echo "					<span class=\"divider\"></span>\n"; 
echo "				</div><a href=\"index.html\" class=\"btn btn-lg btn-seashell\">Unavailable</a><a href=\"index.html\" class=\"btn btn-lg btn-alice-blue\">Request Repair</a>\n"; 
echo "				<h6 class=\"mg-md\">\n"; 
echo "					*Click when unavailable\n"; 
echo "				</h6>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "<!-- bloc-19 END -->\n"; 
echo "\n"; 
echo "<!-- ScrollToTop Button -->\n"; 
echo "<a class=\"bloc-button btn btn-d scrollToTop\" onclick=\"scrollToTarget('1')\"><span class=\"fa fa-chevron-up\"></span></a>\n"; 
echo "<!-- ScrollToTop Button END-->\n"; 
echo "\n"; 
echo "\n"; 
echo "<!-- Footer - bloc-22 -->\n"; 
echo "<div class=\"bloc bgc-black d-bloc\" id=\"bloc-22\">\n"; 
echo "	<div class=\"container bloc-lg\">\n"; 
echo "		<div class=\"row\">\n"; 
echo "			<div class=\"col-sm-3\">\n"; 
echo "				<h3 class=\"mg-md bloc-mob-center-text\">\n"; 
echo "					About\n"; 
echo "				</h3><a href=\"the_team.html\" class=\"a-btn a-block bloc-mob-center-text\">The Team</a><a href=\"contact_us.html\" class=\"a-btn a-block bloc-mob-center-text\">Contact us</a>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"col-sm-3\">\n"; 
echo "				<h3 class=\"mg-md bloc-mob-center-text\">\n"; 
echo "					Book a Ride\n"; 
echo "				</h3><a href=\"renter_login.html\" class=\"a-btn a-block bloc-mob-center-text\">Login</a><a href=\"renter_login.html\" class=\"a-btn a-block bloc-mob-center-text\">Sign Up</a>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"col-sm-3\">\n"; 
echo "				<h3 class=\"mg-md bloc-mob-center-text\">\n"; 
echo "					Follow Us\n"; 
echo "				</h3><a href=\"index.html\" class=\"a-btn a-block bloc-mob-center-text\">Twitter</a><a href=\"index.html\" class=\"a-btn a-block bloc-mob-center-text\">Facebook</a>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"col-sm-3\">\n"; 
echo "				<h3 class=\"mg-md bloc-mob-center-text\">\n"; 
echo "					Company\n"; 
echo "				</h3><a href=\"termspolicy.html\" class=\"a-btn a-block bloc-mob-center-text\">Terms of use</a><a href=\"termspolicy.html\" class=\"a-btn a-block bloc-mob-center-text\">Privacy</a>\n"; 
echo "			</div>\n"; 
echo "		</div>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "<!-- Footer - bloc-22 END -->\n"; 
echo "\n"; 
echo "</div>\n"; 
echo "<!-- Main container END -->\n"; 
echo "    \n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
   }
   
   echo "Fetched data successfully\n";
   
   mysql_close($conn);
?>